# © 2020 Ilya Mateyko. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE.md file.

version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers:
  - astrophena
  assignees:
  - astrophena
